# Generated by Django 2.0.4 on 2018-05-19 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=12)),
                ('nama', models.CharField(max_length=25)),
                ('no_hp', models.IntegerField()),
                ('email', models.CharField(max_length=12)),
                ('foto_guru', models.FileField(upload_to='')),
                ('alamat', models.TextField()),
                ('user_guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=20)),
                ('jurusan', models.CharField(max_length=20)),
                ('nama_guru_wali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guru_siswa.Guru')),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIS', models.IntegerField()),
                ('NISN', models.IntegerField()),
                ('nama_siswa', models.CharField(max_length=50)),
                ('foto_siswa', models.FileField(upload_to='')),
                ('alamat_asal', models.TextField()),
                ('alamat_tinggal', models.TextField()),
                ('no_hp', models.IntegerField()),
                ('email', models.CharField(max_length=23)),
                ('nama_orangtua', models.CharField(max_length=50)),
                ('catatan', models.TextField()),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guru_siswa.Kelas')),
            ],
        ),
    ]
