# Generated by Django 2.0.4 on 2018-05-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='link',
        ),
        migrations.AddField(
            model_name='banner',
            name='text',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
