# Generated by Django 2.0.4 on 2018-05-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_auto_20180521_0548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
