# Generated by Django 2.0.4 on 2018-05-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
                ('publish', models.DateTimeField()),
                ('jadwal_acara', models.DateTimeField()),
                ('ahir_acara', models.DateTimeField()),
                ('deskripsi', models.TextField()),
                ('gambar', models.FileField(blank=True, upload_to='')),
                ('lokasi', models.TextField()),
            ],
        ),
    ]
